### ISSUE TITLE
Cannot create a wallet

### ISSUE THREAD

**Issue by LaggAt** [m2049r/xmrwallet#382]
FATAL EXCEPTION: main
Process: com.m2049r.xmrwallet, PID: 5609
java.security.ProviderException: Failed to load generated key pair from keystore
	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:520)
	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:472)
	at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:723)
	at com.m2049r.xmrwallet.util.KeyStoreHelper.createKeysM(KeyStoreHelper.java:244)
	at com.m2049r.xmrwallet.util.KeyStoreHelper.createKeys(KeyStoreHelper.java:182)
	at com.m2049r.xmrwallet.util.KeyStoreHelper.getCrazyPass(KeyStoreHelper.java:72)
	at com.m2049r.xmrwallet.util.KeyStoreHelper.getCrazyPass(KeyStoreHelper.java:87)
	at com.m2049r.xmrwallet.GenerateFragment.generateWallet(GenerateFragment.java:461)
	at com.m2049r.xmrwallet.GenerateFragment.access$600(GenerateFragment.java:58)
	at com.m2049r.xmrwallet.GenerateFragment$16.onClick(GenerateFragment.java:291)
	at android.view.View.performClick(View.java:6294)
	at android.view.View$PerformClick.run(View.java:24770)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.security.UnrecoverableKeyException: Failed to obtain X.509 form of public key
	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:230)
	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:259)
	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:511)
	... 18 more
Caused by: android.security.KeyStoreException: -22
	at android.security.KeyStore.getKeyStoreException(KeyStore.java:697)
	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:231)
	... 20 more

**Comment by m2049r** [comment]
what device & OS?

**Comment by LaggAt** [comment]
Hi, sorry, didn't see your message earlier.
it's a OnePlus 2 on LineageOS 15.1 rooted.

**Comment by m2049r** [comment]
i suspected as much - this seems like an issue with your device/os combination (see https://stackoverflow.com/questions/44469020/androidkeystore-keypairgenerator-crashes-on-small-number-of-devices for reference).
maybe try a more recent build?
it's difficult to change the key generation procedure because older android versions are limited that way. and we still support back to android 5

**Comment by LaggAt** [comment]
Yea, you 're right. So a LineageOS issue on oneplus2.
Seems it was fixed for a previous version, here the link for reference:
https://jira.lineageos.org/browse/BUGBASH-454?focusedCommentId=13639&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13639
Curious I cannot reproduce the Exception with the app mentionend there. I try to find some time to test those .java files there.

**Comment by m2049r** [comment]
Can you *use* a wallet created on a PC?

**Comment by m2049r** [comment]
@LaggAt can you also try to uninstall/reinstall the app AFTER MAKING SURE YOU HAVE ALL SEEDS & RECOVERY PASSWORDS WRITTEN DOWN?

**Comment by LaggAt** [comment]
Hi, as this wallet is still empty (and never created) I don't care for recovery :)

Wallet from pc created with what? The client from here? https://getmonero.org/downloads/

**Comment by LaggAt** [comment]
Hm ... tested with https://moneroaddress.org/, I cannot create the wallet from mnomic seed nor private keys. 

As this is probably device or rom related, I'll close here and thank you for your effort. Again, if I find some time I'll try to debug it for my droid - a fairly new field for me :) Thank you.

**Comment by m2049r** [comment]
can you please try uninstall/install anyway?

> wallet created on pc

i mean create a wallet on pc and copy the files over to android in monerujo folder and open them there.

**Comment by LaggAt** [comment]
Sure I can. Uninstall/install doesn't help.
Which software should I use on PC to create a compatible wallet file?

**Comment by LaggAt** [comment]
Ok, I found the faq part about using existing wallets here: https://github.com/m2049r/xmrwallet/blob/master/doc/FAQ.md

As I understand I should copy those files only (not the wallet folder) to the /monerujo folder on my droid. I tried this, tried it with folder, and tried both on the /monero folder too, but my phone is never listing the wallet for selection. That said, there is no WalletName.address.txt, just the two other files.

What am I doing wrong?

**Comment by m2049r** [comment]
Just create a WalletName.address.txt file (recent versions of monero don't create it by default) - contents should be the wallet address but actually it can be anything. If you still don't see the wallet,  a restart will help (android does not always scan the folders correctly)

**Comment by LaggAt** [comment]
Yay, it's finally syncing. It was needed to contain the wallet address, otherwise it crashed.

If someone else has this issue:
* Create the wallet in a monero client https://monero.org/monero-clients/
* If missing, create a WalletName.address.txt containing the main address as shown in the client
* Copy these wallet files (on windows in local app data/monero) to /monerujo on the android device, DO NOT create a folder there. Just these 3 files.
* Kill monerujo app if running (or restart your droid)
Wallet should show up when starting the app.

Thanks for all your help, at least I have the app running now. I'll try it with some monero's later :)
